# Generated by Django 2.0.2 on 2018-10-06 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('study_program', '0002_remove_studyprogram_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyprogram',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
