# Generated by Django 2.1.2 on 2018-10-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_program', '0004_studyprogram_pdf_docs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_id', models.CharField(max_length=200)),
                ('academic_title', models.CharField(max_length=200)),
                ('name_surname', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('bsc', models.CharField(max_length=200)),
                ('bsc_grad_institute', models.CharField(max_length=200)),
                ('bsc_year', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=2018, verbose_name='year')),
                ('msc', models.CharField(max_length=200)),
                ('msc_grad_institute', models.CharField(max_length=200)),
                ('msc_year', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=2018, verbose_name='year')),
                ('phd', models.CharField(max_length=200)),
                ('phd_grad_institute', models.CharField(max_length=200)),
                ('phd_year', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=2018, verbose_name='year')),
                ('phone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=200)),
                ('additional_degree', models.CharField(blank=True, max_length=200)),
                ('assessment_committee', models.CharField(blank=True, max_length=200, verbose_name='Committee')),
                ('responsible_program', models.ManyToManyField(blank=True, to='study_program.StudyProgram')),
            ],
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='responsible_professors',
            field=models.ManyToManyField(blank=True, to='study_program.Professor'),
        ),
    ]
