# Generated by Django 2.0 on 2019-05-13 16:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_program', '0004_auto_20190226_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_for', models.CharField(max_length=50)),
                ('sender', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=50)),
                ('sender', models.CharField(max_length=50)),
                ('sending_time', models.DateTimeField(default=datetime.datetime(2019, 5, 13, 23, 0, 17, 912595))),
                ('topic', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=400)),
            ],
        ),
        migrations.RemoveField(
            model_name='availabletime',
            name='appointment_time',
        ),
        migrations.AddField(
            model_name='availabletime',
            name='available_in_afternoon',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=400),
        ),
        migrations.AddField(
            model_name='availabletime',
            name='available_in_morning',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=400),
        ),
        migrations.AlterField(
            model_name='aun',
            name='assessment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='study_program.AssessmentResult'),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='appointed_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='study_program.StudyProgram'),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='appointment_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
