# Generated by Django 2.1.2 on 2018-10-23 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_program', '0006_committee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='assessment_committee',
        ),
        migrations.AddField(
            model_name='professor',
            name='committee_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='study_program.Committee'),
        ),
    ]
