# Generated by Django 2.1.2 on 2018-10-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_program', '0007_auto_20181023_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='committee_profile',
        ),
        migrations.AddField(
            model_name='professor',
            name='committee_profile',
            field=models.ManyToManyField(blank=True, to='study_program.Committee'),
        ),
    ]
