# Generated by Django 2.1.2 on 2018-10-23 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_program', '0009_auto_20181023_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentresult',
            name='professor_id',
        ),
    ]
