# Generated by Django 2.1.2 on 2018-10-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_program', '0011_auto_20181023_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='assessment_programs',
            field=models.ManyToManyField(blank=True, to='study_program.AssessmentResult'),
        ),
    ]
