# Generated by Django 2.1.2 on 2018-10-23 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_program', '0012_committee_assessment_programs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AUN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('criteria1', models.IntegerField()),
                ('criteria2', models.IntegerField()),
                ('criteria3', models.IntegerField()),
                ('criteria4', models.IntegerField()),
                ('criteria5', models.IntegerField()),
                ('criteria6', models.IntegerField()),
                ('criteria7', models.IntegerField()),
                ('criteria8', models.IntegerField()),
                ('criteria9', models.IntegerField()),
                ('criteria10', models.IntegerField()),
                ('criteria11', models.IntegerField()),
                ('total_score', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='aun_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='study_program.AUN'),
        ),
    ]
