# Generated by Django 2.1.2 on 2018-10-23 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_program', '0013_auto_20181023_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='aun',
            name='assessment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='study_program.AssessmentResult'),
        ),
    ]
