# Generated by Django 2.1.2 on 2018-12-18 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_program', '0015_remove_aun_assessment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentresult',
            name='aun_id',
        ),
        migrations.RemoveField(
            model_name='aun',
            name='code',
        ),
        migrations.AddField(
            model_name='aun',
            name='assessment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='study_program.AssessmentResult'),
        ),
    ]
