# Generated by Django 2.1.2 on 2018-12-18 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_program', '0017_auto_20181219_0416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='committee_profile',
        ),
    ]
