# Generated by Django 2.1.2 on 2018-12-31 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_program', '0018_remove_professor_committee_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyprogram',
            name='past_assessment',
        ),
    ]
