# Generated by Django 2.1.2 on 2019-01-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_program', '0020_auto_20190127_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyprogram',
            name='collaboration_with_other_institues',
            field=models.CharField(choices=[('Program issued specifically by KMITL', 'Program issued specifically by KMITL'), ('Program supported by other institutes', 'Program supported by other institutes'), ('Collaborated program with other institutes', 'Collaborated program with other institutes')], max_length=400),
        ),
    ]
